unique_ids:
  assets:
    standard-page.html: NIRQORMFAZWMYX5ZABX5WH6F4LPIHW4Y
    theme.css: MHME3XYCL36EBAKV3SX6FZQSTOMXMO45
  forms:
    Form1: IZZUYJH5T3ME2BQ7XQH4AXWMUOOFHW3Z
    DashboardForm: DASHBOARD01ABCDEFGHIJKLMNOPQRST
    PersonenForm: PERSONEN01ABCDEFGHIJKLMNOPQRSTU
    FahrzeugeForm: FAHRZEUGE01ABCDEFGHIJKLMNOPQRS
    LagerForm: LAGERFORM01ABCDEFGHIJKLMNOPQRSTU
    WaffenMunitionForm: WAFFENMUN01ABCDEFGHIJKLMNOP
  modules: {}
  scripts: {}
  server_modules:
    ServerModule: SERVERMOD01ABCDEFGHIJKLMNOPQRS
